# TODO: Define the Workflow Name 
name: Project CI/CD Pipeline

# TODO: Define triggers for the workflow
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  # TODO: Define a job for building and testing the frontend
  frontend:
    runs-on: ubuntu-latest
    steps:
      # TODO: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
      
      # TODO: Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' #frontend dockerfile using node:14-alpine
      
      # TODO: Install dependencies ; navigate to frontend folder 
      - name: Install dependencies 
        run: |
          cd frontend 
          npm install 
      
      # TODO: Build the React app
      - name: Build React app
        run: |
          cd frontend
          npm run build

  # TODO: Define a job for building and testing the backend
  backend:
    runs-on: ubuntu-latest
    steps:
      # TODO: Checkout code
      - uses: actions/checkout@v2
      
      # TODO: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' #backend dockerfile using python:3.9-slim

      # TODO: Install dependencies
      - name: Install dependencies
        run: | 
          cd backend
          pip install -r requirements.txt
      
      # TODO: Run tests
      - name: Run test
        run: | 
          cd backend
          pytest

  # TODO: Define a job for building and pushing Docker images
  docker:
    # Run this job only when 'frontend' & 'backend' stages are sucessfully completed
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      # TODO: Checkout code
      - uses: actions/checkout@v2
      
      # TODO: Setup Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker Hub credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # TODO: Build frontend Docker image
      - name: Build Docker Image
        run: |
          docker build -t carmahn/frontend:${{ github.sha }} ./frontend

      - name: Push Docker Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push carmahn/frontend:${{ github.sha }}

      # TODO: Build backend Docker image
      - name: Build backend Docker image
        run: |
          docker build -t carmahn/backend:${{ github.sha }} ./backend
      # TODO: Push images to Docker Hub (if on main branch)
      - name: Push backend Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push carmahn/backend:${{ github.sha }}
